[loggers]
keys = root, dad

[handlers]
keys = rootHandler, dadHandler

[formatters]
keys = rootFormatter

[logger_root]
level = INFO
handlers = rootHandler

[logger_dad]
level = INFO
handlers = dadHandler
qualname = dad
propagate = 0



[handler_rootHandler]
class = FileHandler
level = INFO
formatter = rootFormatter
args = ('log/flow.log',)

[handler_dadHandler]
class = FileHandler
level = INFO
formatter = rootFormatter
args = ('log/dungeon_and_dragon.log',)

[formatter_rootFormatter]
format = %(name)s - %(levelname)s - %(message)s - %(asctime)s